<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>gekos_api</AssemblyName>
    <RootNamespace>gekos_api</RootNamespace>
    <OutputType>Library</OutputType>
    <Version>0.5.1</Version>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GameRoot>$(MSBuildProjectDirectory)\..\..\..\..</GameRoot>
    <StagingDir>$(MSBuildProjectDirectory)\..\..\Build\$(Configuration)\BepInEx\plugins\gekos_api</StagingDir>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="PhysicsModule" HintPath="$(GameRoot)\EscapeFromTarkov_Data\Managed\UnityEngine.PhysicsModule.dll" Private="false" />
    <Reference Include="0Harmony" HintPath="$(GameRoot)\BepInEx\core\0Harmony.dll" Private="false" />
    <Reference Include="spt-common" HintPath="$(GameRoot)\BepInEx\plugins\spt\spt-common.dll" Private="false" />
    <Reference Include="spt-reflection" HintPath="$(GameRoot)\BepInEx\plugins\spt\spt-reflection.dll" Private="false" />
    <Reference Include="Assembly-CSharp" HintPath="$(GameRoot)\EscapeFromTarkov_Data\Managed\Assembly-CSharp.dll" Private="false" />
    <Reference Include="BepInEx" HintPath="$(GameRoot)\BepInEx\core\BepInEx.dll" Private="false" />
    <Reference Include="Comfort" HintPath="$(GameRoot)\EscapeFromTarkov_Data\Managed\Comfort.dll" Private="false" />
    <Reference Include="Comfort.Unity" HintPath="$(GameRoot)\EscapeFromTarkov_Data\Managed\Comfort.Unity.dll" Private="false" />
    <Reference Include="Newtonsoft.Json" HintPath="$(GameRoot)\EscapeFromTarkov_Data\Managed\Newtonsoft.Json.dll" Private="false" />
    <Reference Include="Sirenix.Serialization" HintPath="$(GameRoot)\EscapeFromTarkov_Data\Managed\Sirenix.Serialization.dll" Private="false" />
    <Reference Include="Unity.TextMeshPro" HintPath="$(GameRoot)\EscapeFromTarkov_Data\Managed\Unity.TextMeshPro.dll" Private="false" />
    <Reference Include="UnityEngine" HintPath="$(GameRoot)\EscapeFromTarkov_Data\Managed\UnityEngine.dll" Private="false" />
    <Reference Include="UnityEngine.AssetBundleModule" HintPath="$(GameRoot)\EscapeFromTarkov_Data\Managed\UnityEngine.AssetBundleModule.dll" Private="false" />
    <Reference Include="UnityEngine.CoreModule" HintPath="$(GameRoot)\EscapeFromTarkov_Data\Managed\UnityEngine.CoreModule.dll" Private="false" />
    <Reference Include="UnityEngine.IMGUIModule" HintPath="$(GameRoot)\EscapeFromTarkov_Data\Managed\UnityEngine.IMGUIModule.dll" Private="false" />
    <Reference Include="UnityEngine.InputLegacyModule" HintPath="$(GameRoot)\EscapeFromTarkov_Data\Managed\UnityEngine.InputLegacyModule.dll" Private="false" />
    <Reference Include="UnityEngine.TextRenderingModule" HintPath="$(GameRoot)\EscapeFromTarkov_Data\Managed\UnityEngine.TextRenderingModule.dll" Private="false" />
    <Reference Include="UnityEngine.UI" HintPath="$(GameRoot)\EscapeFromTarkov_Data\Managed\UnityEngine.UI.dll" Private="false" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Assets\skillsbutton.bundle" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <Target Name="StageClientPlugin" AfterTargets="Build">
    <MakeDir Directories="$(StagingDir)\Assets" />
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(StagingDir)" />
    <Copy SourceFiles="Assets\skillsbutton.bundle" DestinationFolder="$(StagingDir)\Assets" />
  </Target>
</Project>
