<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>GekosBetterProgression</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <OutputType>Library</OutputType>
        <Version>2.1.0</Version>
        <DebugType>none</DebugType>
        <DebugSymbols>false</DebugSymbols>
        <!-- The two lines below will set the output path for the binaries -->
        <OutputPath>$(MSBuildProjectDirectory)\..\..\..\..\Build\$(Configuration)\SPT_Runtime\user\mods\GekosBetterProgression\</OutputPath>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="SPTarkov.Common" Version="4.1.2" />
        <PackageReference Include="SPTarkov.DI" Version="4.1.2" />
        <PackageReference Include="SPTarkov.Reflection" Version="4.1.2" />
        <PackageReference Include="SPTarkov.Server.Core" Version="4.1.2" />
    </ItemGroup>

    <ItemGroup>
        <None Update="config.json5">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="advancedConfig.json5">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
    </ItemGroup>

</Project>
